name: Terraform Apply
on:
  push:
    


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7
    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - name: Terraform Init
      run: terraform init
    - name: Print secret value
      env:
        
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      
      run: |
          echo $AWS_SECRET_KEY
          echo $AWS_SECRET_ACCESS_KEY
      
        
    - name: Terraform Plan
      run: |
          terraform plan -var aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }} -var aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}
        
    - name: Terraform Apply
      # continue-on-error: true
      # if: github.ref == 'refs/heads/main'
      run: |
          terraform apply --auto-approve -var aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }} -var aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}